###
GET http://localhost:3000/users/

####
GET http://localhost:3000/users/3


//TAREA CREAR USUARIO
###
POST http://localhost:3000/users/
Content-Type: application/json

{
"username":"PANCHO VILLA",
"password":"panchita",
"email": "pan@cho.com"

}


###
//ACTUALIZAR USUARIO
PUT  http://localhost:3000/users/7
Content-Type: application/json

{
"username":"PANCHO VILLA JR",
"password":"pANCHON",
"email": "pancho@chocho.com"
}

//ELIMINAR 
###
DELETE  http://localhost:3000/users/8 
# Content-Type: application/json

# {
# "name": "LUIS carlos alfred"

# }

//ESTE ME LO PASO EL IRVING 

###
GET http://localhost:3000/users/ 

###
GET http://localhost:3000/users/1


###
GET http://localhost:3000/users/3/


###
POST http://localhost:3000/users/
Content-Type: application/json

{
  "name": "cambiale" 
  
}


###
PUT http://localhost:3000/users/2
Content-Type: application/json

{
  "name": "cambiale" 
  
}


###
DELETE http://localhost:3000/users/5/