GET http://localhost:3000/usuarios


###
GET http://localhost:3000/usuarios/a

###
POST  http://localhost:3000/usuarios/
Content-Type: application/json

{
    "nombre": "julio",
    "apellido" : "Aguilar",
    "email" : "julio@gmail.com"

}

